apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    tier: backend
---
apiVersion: v1
kind: Pod
metadata:
  name: redis6
  labels:
    app: redis
    tier: backend
spec:
  containers:
  - name: redis
    image: redis:6.0
    env:
      - name: TZ
        value: Asia/Shanghai
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /data/redis
      subPath: redis
    imagePullPolicy: IfNotPresent
  volumes:
  - name: redis-persistent-storage
    persistentVolumeClaim:
      claimName: redis-pv-claim
