apiVersion: v1
kind: Pod
metadata:
  name: redis6
spec:
  containers:
  - name: redis
    image: redis:6.0
    volumeMounts:
    - name: redis-storage
      mountPath: /data/kube/redis
    imagePullPolicy: IfNotPresent
  volumes:
  - name: redis-storage
    emptyDir: {}
